// src/app/trails/page.tsx
import { TrailCard } from '@/modules/trail/components/trail-card';
import { groupTrailsByCategory } from '@/modules/trail/lib/group-trails-by-category';
import { GetTrailsUseCase } from '@/modules/trail/use-cases/get-trails-use-case';
import coatiSvg from '@/shared/assets/images/coati.svg';
import { Button } from '@/shared/components/ui/button';
import { Input } from '@/shared/components/ui/input';
import Image from 'next/image';

type PageProps = {
  searchParams: {
    search?: string;
  };
};

export default async function Page(props: PageProps) {
  const getTrailsUseCase = new GetTrailsUseCase();
  const trails = await getTrailsUseCase.execute({ search: props.searchParams.search });
  const trailsGroupedByCategory = groupTrailsByCategory(trails);

  return (
    <main className="py-8 container">
      <form action="/trails" method="get" className="flex items-center justify-center space-x-2 mb-8">
        <Input type="text" name="search" placeholder="Buscar trilha" />
        <Button type="submit">Buscar</Button>
      </form>

      {trails.length === 0 && (
        <div className="flex flex-col items-center justify-center space-y-2 gap-4">
          <h2 className="text-xl">Nenhuma trilha encontrada</h2>
          <Image src={coatiSvg} alt="Coati" width={200} height={200} className="opacity-30" />
          <p className="text-muted-foreground">Tente buscar por outra trilha</p>
        </div>
      )}

      {trailsGroupedByCategory.map(([category, trails]) => (
        <section key={category}>
          <h2 className="text-2xl font-bold">{category}</h2>
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 mt-4">
            {trails.map(trail => (
              <TrailCard key={trail.id} trail={trail} />
            ))}
          </div>
        </section>
      ))}
    </main>
  );
}

// src/routes/admin/trails/+page.svelte
<script lang="ts">
	import { AdminSection } from '$lib/components/admin-section';
	import { Button } from '$lib/components/button';
	import { Input } from '$lib/components/input';
	import { TrailCard } from '$lib/components/trail-card';

	export let data;
</script>

<AdminSection title="Gerenciar conteúdo">
	<form class="lc-box flex flex-col gap-4" method="POST" action="?/createTrail">
		<h2 class="text-2xl font-bold">Criar trilha</h2>
		<Input variant="opaque" id="title" label="Título" name="title" />
		<Input variant="opaque" id="description" label="Descrição" name="description" />
		<Input variant="opaque" id="image" label="Imagem" name="image" />

		<!-- image drag and drop image upload area -->
		<div
			class="flex flex-col items-center justify-center w-full h-32 border-2 border-dashed rounded-md bg-white/90 border-purple-300"
		>
			<div class="flex flex-col items-center justify-center w-full h-full text-center">
				<p class="text-sm font-semibold text-purple-500">
					Arraste e solte a imagem aqui ou clique para selecionar
				</p>
				<input type="file" class="hidden" />
			</div>
		</div>

		<Button type="submit">Criar</Button>
	</form>
</AdminSection>

<div class="grid grid-cols-1 gap-4 mt-8 sm:grid-cols-2">
	{#each data.trails as trail}
		<TrailCard {trail} />
	{/each}
</div>
