// src/lib/components/trail-card/trail-card.svelte
<script lang="ts">
	import { Button } from '$lib/components/button';
	import type { Trail } from '$modules/trail/types/trail';
	import { ArrowRightIcon, Edit } from 'lucide-svelte';
	import { ContributorAvatarGroup } from '../contributor-avatar-group';

	export let trail: Trail;

	export let editable = false;
</script>

<a href={trail.slug} class="relative flex flex-col w-full bg-white rounded-md overflow-clip border border-white/25">
	<ContributorAvatarGroup className="absolute top-4 right-4" contributors={trail.contributors} />

	<img class="object-cover w-full h-96 lg:h-80" src={trail.thumbnail} alt={trail.title} />

	<div class="p-4 h-full flex flex-col justify-between">
		<div>
			<h2 class="text-2xl font-black uppercase min-h-[2lh] line-clamp-2 break-words">{trail.title}</h2>
			<p class="mt-2 text-sm text-gray-800 w-full min-h-[4lh] line-clamp-4 break-words">{trail.description}</p>

			<time class="block mt-2 text-sm text-gray-500" datetime={trail.updatedAt.toISOString()}>
				Atualizado em {new Date(trail.updatedAt).toLocaleDateString()}
			</time>
		</div>

		<div class="w-full flex gap-2 mt-4">
			<Button className="w-full" href={trail.slug}>
				Ver mais
				<ArrowRightIcon size={18} />
			</Button>

			{#if editable}
				<Button size="icon" href="/admin/trails/{trail.id}" title="Editar trilha">
					<Edit size={18} />
				</Button>
			{/if}
		</div>
	</div>
</a>

// src/modules/trail/components/trail-card/index.tsx
import type { User } from '@/modules/user/types/user';
import {
  Avatar,
  AvatarFallback,
  AvatarImage,
} from '@/shared/components/ui/avatar';
import { Button } from '@/shared/components/ui/button';
import { ArrowRightIcon } from 'lucide-react';
import Image from 'next/image';
import Link from 'next/link';
import { type Trail } from '../../types/trail';

type TrailCardProps = {
  trail: Trail;
  author?: User;
};

export function TrailCard({ trail, author }: TrailCardProps) {
  const trailSlug = `/trails/${trail.id}`;
  const userProfileSlug = author ? `/profile/${author.username}` : '';

  return (
    <article className="flex flex-col justify-center items-center w-full bg-card text-card-foreground rounded-xl shadow-md overflow-hidden hover:shadow-lg transition-shadow duration-300 ease-in-out border">
      <div className="relative h-96 w-full">
        <Link href={trailSlug}>
          <Image
            fill
            alt={trail.title}
            src={trail.thumbnail}
            className="object-cover object-center w-full"
          />
        </Link>

        {author && (
          <div className="absolute bottom-2 left-2 flex gap-2">
            <Link href={userProfileSlug}>
              <Avatar>
                <AvatarFallback>{author.username.slice(0, 2)}</AvatarFallback>
                <AvatarImage src={author.avatar} alt={author.username} />
              </Avatar>
            </Link>
          </div>
        )}
      </div>

      <div className="p-4 w-full h-fit flex flex-col justify-between">
        <div>
          <h2 className="text-2xl font-black uppercase min-h-[2lh] line-clamp-2 break-words">
            {trail.title}
          </h2>
          <p className="mt-2 text-sm text-card-foreground/75 w-full min-h-[4lh] line-clamp-4 break-words">
            {trail.description}
          </p>

          <time
            className="block mt-2 text-sm text-card-foreground-500"
            dateTime={trail.updatedAt}
          >
            Atualizado em {new Date(trail.updatedAt).toLocaleString()}
          </time>
        </div>

        <div className="w-full flex gap-2 mt-4">
          <Button asChild className="w-full">
            <Link href={trailSlug}>
              Ver mais
              <ArrowRightIcon size={18} />
            </Link>
          </Button>
        </div>
      </div>
    </article>
  );
}
