// src/lib/components/header/header.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import { isAdministrator } from '$modules/user/constants/user-roles';
	import type { AuthUser } from '$modules/user/schemas/auth-user';
	import { BrainIcon } from 'lucide-svelte';
	import Dialog from './dialog.svelte';
	import NavItem from './nav-item.svelte';

	export let user: AuthUser | null = null;
</script>

<header
	class="sticky top-0 z-10 bg-black/25 text-white h-[var(--header-height)] border-b-[1px] border-white/10 backdrop-blur-md flex items-center justify-between p-2"
>
	<a title="coati" href="/">
		<BrainIcon class="w-8 h-8 text-white/80 fill-white" />
	</a>

	<Dialog>
		<nav class="flex flex-col gap-3 p-3 z-50">
			<NavItem href="/trails">Conhecer trilhas</NavItem>

			{#if user && isAdministrator(user.roles)}
				<NavItem href="/admin">Painel administrativo</NavItem>
			{/if}

			{#if user}
				<NavItem href="/profile">Olá {user.username}</NavItem>

				<form use:enhance method="post" action="/api/sign-out">
					<NavItem>Sair</NavItem>
				</form>
			{:else}
				<NavItem href="/sign-in">Entrar</NavItem>
			{/if}
		</nav>
	</Dialog>

	<nav class="hidden md:flex items-center gap-4">
		<a href="/trails" class="p-2">Conhecer trilhas</a>

		{#if user}
			<form use:enhance method="POST" action="/sign-out">
				<button type="submit">Sair</button>
			</form>

			<a href="/profile" class="p-2">Olá {user.username}</a>

			{#if isAdministrator(user.roles)}
				<a href="/admin" class="p-2">Painel administrativo</a>
			{/if}
		{:else}
			<a href="/sign-in" class="p-2">Entrar</a>
		{/if}
	</nav>
</header>

// src/shared/components/common/header/index.tsx
import { SignOutAction } from '@/modules/auth/components/sign-out-action';
import { roles } from '@/modules/auth/constants/roles';
import { getPageSession } from '@/modules/auth/helpers/get-page-session';
import logoImage from '@/shared/assets/images/favicon.svg';
import { Button } from '@/shared/components/ui/button';
import Image from 'next/image';
import Link from 'next/link';

export async function Header() {
  const session = await getPageSession();

  const hasAdminAccess = session !== null && session.user.role === roles.ADMIN;

  return (
    <header className="top-0 sticky border-b h-[--header-height] bg-background/75 backdrop-blur-md">
      <div className="flex items-center justify-between container h-full">
        <Link href="/" className="flex item-center gap-2">
          <Image src={logoImage} alt="CoatiQuati" />
          <h1 className="text-xl font-bold">CoatiQuati</h1>
        </Link>

        <div className="flex items-center gap-2">
          <Button variant="ghost" asChild>
            <Link href="/trails">Trilhas</Link>
          </Button>

          <Button variant="ghost" asChild>
            <Link href="/about">Sobre</Link>
          </Button>

          {hasAdminAccess && (
            <Button variant="ghost" asChild>
              <Link href="/dashboard">Dashboard</Link>
            </Button>
          )}

          {session !== null ? (
            <Button variant="ghost" asChild>
              <SignOutAction>Sair</SignOutAction>
            </Button>
          ) : (
            <Button variant="ghost" asChild>
              <Link href="/sign-in">Entrar</Link>
            </Button>
          )}
        </div>
      </div>
    </header>
  );
}
