// src/lib/components/input/input.svelte
<script lang="ts">
	export let label: string;
	export let id: string;
</script>

<div class="flex flex-col gap-2 mb-4">
	<label class="font-bold text-white text-md" for={id}>{label}</label>
	<input
		{id}
		{...$$restProps}
		class={`w-full p-2 rounded-md text-white bg-white/10 border-b border-white/50 outline-none focus:border-white/80 ${$$props.class}`}
	/>
</div>

// src/shared/components/ui/input.tsx
import * as React from 'react';

import { cn } from '@/shared/utils/cn';

export interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {}

const Input = React.forwardRef<HTMLInputElement, InputProps>(({ className, type, ...props }, ref) => {
  return (
    <input
      type={type}
      className={cn(
        'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
        className,
      )}
      ref={ref}
      {...props}
    />
  );
});
Input.displayName = 'Input';

export { Input };
